package com.ec.model.enums;

public enum StatusLogging {
	LOGIN_SUCCESFULLY,
	LOGIN_FAILED,
	LOGGED_OFF,
	ALREADY_LOGGED_ON, 
	WRONG_PASSWORD, 
	WRONG_MAIL, 
	WRONG_ID_CLIENT, ALREADY_LOGGED_OFF, CLIENT_NOT_FOUND
}
